# GitLab CI configuration - https://docs.gitlab.com/ce/ci/yaml/README.html
# r10k or similar.
variables:
  GIT_STRATEGY: clone
  PATH: /opt/puppetlabs/puppet/bin:/usr/bin:/usr/sbin:/bin:/sbin

stages:
  - merge request
  - checks
  - impact
  - promote

# Create WIP Merge request
Create WIP MR:
  stage: merge request
  script:
    - "bin/gitlab_multirepo_create_merge_request.rb psick-hieradata ${CI_BUILD_REF_NAME} production \"WIP: Works on ${CI_BUILD_REF_NAME}\"" 
  when: on_success
  tags:
    - deploy_puppet
  except:
    - production
    - schedules
  allow_failure: true

Syntax checks:
  stage: checks
  script: "bin/yaml_check_syntax.sh"
  tags:
    - test_puppet
  except:
    - production
  only:
    - branches

Impact checks:
  stage: impact
  script: "bin/check_changed_files.sh data/nodes data/role"
  tags:
    - test_puppet
  except:
    - production
  only:
    - branches

Accept MR:
  stage: promote
  script: "bin/gitlab_multirepo_accept_merge_request.rb psick-hieradata ${CI_BUILD_REF_NAME} production"
  tags:
    - deploy_puppet
  when: on_success
  except:
    - production
  only:
    - branches

